use std::{
    collections::{BTreeMap, BTreeSet},
    env,
    fmt::Write as _,
    fs,
    path::PathBuf,
};

use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegionCatalog {
    regions: Vec<RegionDefinition>,
    direct_aliases: BTreeMap<String, String>,
    group_aliases: BTreeMap<String, Vec<String>>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegionDefinition {
    id: String,
    label: String,
    sensor_code: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let catalog_path = manifest_dir.join("src/regions.catalog.json");
    println!("cargo:rerun-if-changed={}", catalog_path.display());

    let catalog_json = fs::read_to_string(&catalog_path).expect("failed to read region catalog");
    let catalog: RegionCatalog =
        serde_json::from_str(&catalog_json).expect("failed to parse region catalog");
    validate_catalog(&catalog);

    let generated = render_catalog(&catalog);
    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("missing out dir")).join("regions_generated.rs");
    fs::write(out_path, generated).expect("failed to write generated region tables");
}

fn validate_catalog(catalog: &RegionCatalog) {
    let region_ids = catalog
        .regions
        .iter()
        .map(|region| region.id.as_str())
        .collect::<BTreeSet<_>>();
    if region_ids.len() != catalog.regions.len() {
        panic!("region catalog contains duplicate region ids");
    }

    let sensor_codes = catalog
        .regions
        .iter()
        .map(|region| region.sensor_code.as_str())
        .collect::<BTreeSet<_>>();
    if sensor_codes.len() != catalog.regions.len() {
        panic!("region catalog contains duplicate sensor codes");
    }

    let mut const_names = BTreeMap::new();
    for region in &catalog.regions {
        let const_name = to_const_name(&region.id);
        let Some(first_character) = const_name.chars().next() else {
            panic!("region id {} generates an empty const name", region.id);
        };
        if !matches!(first_character, 'A'..='Z' | '_') {
            panic!(
                "region id {} generates invalid const name {}",
                region.id, const_name
            );
        }
        if let Some(existing_region) = const_names.insert(const_name.clone(), region.id.as_str()) {
            panic!(
                "region ids {} and {} both normalize to const name {}",
                existing_region, region.id, const_name
            );
        }
    }

    if catalog
        .direct_aliases
        .keys()
        .any(|alias| catalog.group_aliases.contains_key(alias))
    {
        panic!("region catalog alias is present in both direct_aliases and group_aliases");
    }

    for canonical_region in catalog.direct_aliases.values() {
        if !region_ids.contains(canonical_region.as_str()) {
            panic!("unknown direct alias target: {canonical_region}");
        }
    }

    for (alias, grouped_regions) in &catalog.group_aliases {
        if grouped_regions.is_empty() {
            panic!("group alias {alias} cannot be empty");
        }

        for canonical_region in grouped_regions {
            if !region_ids.contains(canonical_region.as_str()) {
                panic!("unknown grouped alias target: {canonical_region}");
            }
        }
    }
}

fn render_catalog(catalog: &RegionCatalog) -> String {
    let mut generated = String::from("// generated by crates/scemas-core/build.rs\n");

    for region in &catalog.regions {
        writeln!(
            generated,
            "pub const {}: &str = {};",
            to_const_name(&region.id),
            rust_string(&region.id),
        )
        .expect("failed to write generated region constant");
    }
    generated.push('\n');

    generated.push_str("pub const CANONICAL_REGION_IDS: &[&str] = &[\n");
    for region in &catalog.regions {
        writeln!(generated, "    {},", to_const_name(&region.id))
            .expect("failed to write canonical region id");
    }
    generated.push_str("];\n\n");

    generated.push_str("const REGIONS: &[RegionEntry] = &[\n");
    for region in &catalog.regions {
        writeln!(
            generated,
            "    ({}, {}, {}),",
            to_const_name(&region.id),
            rust_string(&region.label),
            rust_string(&region.sensor_code),
        )
        .expect("failed to write region entry");
    }
    generated.push_str("];\n\n");

    generated.push_str("const DIRECT_ZONE_ALIASES: &[DirectZoneAliasEntry] = &[\n");
    for (alias, canonical_region) in &catalog.direct_aliases {
        writeln!(
            generated,
            "    ({}, {}),",
            rust_string(alias),
            to_const_name(canonical_region),
        )
        .expect("failed to write direct alias");
    }
    generated.push_str("];\n\n");

    generated.push_str("const GROUPED_ZONE_ALIASES: &[GroupedZoneAliasEntry] = &[\n");
    for (alias, grouped_regions) in &catalog.group_aliases {
        let canonical_regions = grouped_regions
            .iter()
            .map(|region| to_const_name(region))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            generated,
            "    ({}, &[{}]),",
            rust_string(alias),
            canonical_regions,
        )
        .expect("failed to write grouped alias");
    }
    generated.push_str("];\n");

    generated
}

fn to_const_name(value: &str) -> String {
    value
        .chars()
        .map(|character| match character {
            'a'..='z' | 'A'..='Z' | '0'..='9' => character.to_ascii_uppercase(),
            _ => '_',
        })
        .collect()
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}
